### ISSUE TITLE
Upgrade to the latest Spring Cloud Build, Spring Cloud Deployer for 1.1.x

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-scheduler#30]
The `spring-cloud-build` parent needs to be in sync with what SCDF 2.x uses. 

This implicitly brings in the Spring Boot 2.1.x upgrade as well.

**Comment by sabbyanandan** [comment]
We need to decide whether or not we will continue on the 1.x (vs) bumping the release version to 2.x since the underlying libraries are on major release-line.

**Comment by sabbyanandan** [comment]
cc: @ilayaperumalg @chrisjs
